#!/bin/sh
#PBS -q normal
#PBS -N NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B
#PBS -l walltime=00:30:00
#PBS -o scheduler_stdout.txt
#PBS -e scheduler_stderr.txt
##PBS -V

#PBS -v QOS=2

#PBS -M  nsgprod@sdsc.edu
#PBS -m ae
#PBS -A csd403
#PBS -l nodes=1:ppn=32
cd /projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B/Case7Model

source /etc/profile.d/modules.sh
echo Job starting at `date` > ../start.txt
curl http://nsgdev.sdsc.edu:8080/portal2/taskupdate.action?taskId=12807\&status=START
export CIPRES_THREADSPP=1
export CIPRES_NP=1
export NPROCS=`wc -l < $PBS_NODEFILE`
/projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B/./batch_command.cmdline 1>/projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B/stdout.txt 2>/projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B/stderr.txt
cd /projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B
/bin/tar -cvzf output.tar.gz ./*
#/bin/tar -cvzf ../output.tar.gz ../*
echo Job finished at `date` > done.txt
curl http://nsgdev.sdsc.edu:8080/portal2/taskupdate.action?taskId=12807\&status=DONE
/projects/ps-nsg/home/nsguser/ngbw/contrib/scripts/copy_output.sh NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B /projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B
