#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/projects/ps-nsg/home/nsguser/applications/neuron7.3/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/projects/ps-nsg/home/nsguser/applications/neuron7.3/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/projects/ps-nsg/home/nsguser/ngbw/workspace/NGBW-JOB-NEURON73_TG-1588248102084D1399E01BF0648C672B/Case7Model/x86_64/.libs/libnrnmech.so" "$@"
