#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/Applications/NEURON-7.4/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/Applications/NEURON-7.4/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/alexgm/Desktop/SkinnerLab/Usages/Simulation Dendritic Recordings/SD50TopModels/Case8StarModel/x86_64/.libs/libnrnmech.so" "$@"
